version: '3.1'
services:
  web:
    build: .
    restart: always
    environment:
      - DB_PASS=test
      - DB_USER=root
      - DB_NAME=alpha
      - DB_HOST=db
    ports:
      - 8080:8080
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080